stages:
    - compile
    - checkstyle
    - docker_build

cache:
    key: mavenrepo
    paths:
        - ./.m2/repository/


build wicket-static:
    stage: compile
    image: maven:3.8.5-amazoncorretto-11
    script:
        - mvn clean install package
    artifacts:
        paths:
            - /builds

build checkstyle:
    stage: checkstyle
    image: maven:3.8.5-amazoncorretto-11
    script:
        - mvn checkstyle:check

build docker images:
    stage: docker_build
    script:
        - apk update
        - apk add --no-cache bash
        - chmod +x start-container.sh
        - cp /builds/hmeftah/wicket-static/target/wicket-static-1.0-SNAPSHOT.war .
        - docker build -t wicket-app  .
        - ./start-container.sh




        


      

